graphql:
  annotations:
    basePackage: com.example.demo
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: latest
#  props:
##    resources:
##      query: query.graphql
##      defaultQuery: defaultQuery.graphql
##      variables: variables.graphql
##    variables:
##      editorTheme: "solarized light"
  headers:
    Authorization: "Bearer <your-token>"
  props:
    variables:
      headerEditorEnabled: true
server:
  port: 4002